//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerGarage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeRegistry
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "First Name is required")]
        public string EmployeeFirstName { get; set; }
        [Required(ErrorMessage = "Last Name is required")]
        public string EmployeeLastName { get; set; }
        [Required(ErrorMessage = "Contact Number is required")]
        public long EmployeeContact { get; set; }
        [Required(ErrorMessage = "Email Id is required")]
        public string EmployeeEmailId { get; set; }
        [Required(ErrorMessage = "Password is required")]
        public string EmployeePassword { get; set; }
       

        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
