//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRegistry
    {
        public int Id { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public long EmployeeContact { get; set; }
        public string EmployeeEmailId { get; set; }
        public string EmployeePassword { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
