//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerGarage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GerGarageDbEntities : DbContext
    {
        public GerGarageDbEntities()
            : base("name=GerGarageDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerLogin> CustomerLogins { get; set; }
        public virtual DbSet<CustomerRegistry> CustomerRegistries { get; set; }
        public virtual DbSet<EmployeeLogin> EmployeeLogins { get; set; }
        public virtual DbSet<EmployeeRegistry> EmployeeRegistries { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }
        public virtual DbSet<CustomerBooking> CustomerBookings { get; set; }
        public virtual DbSet<VehicleMake> VehicleMakes { get; set; }
        public virtual DbSet<ServicesAvailable> ServicesAvailables { get; set; }
        public virtual DbSet<BookingStatusTable> BookingStatusTables { get; set; }
        public virtual DbSet<JobCardDetail> JobCardDetails { get; set; }
        public virtual DbSet<CustomersBooking> CustomersBookings { get; set; }
        public virtual DbSet<JobDetail> JobDetails { get; set; }
    }
}
